# Generated by Django 5.0.2 on 2024-02-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Technology', 'Technology and Gadgets'), ('Lifestyle', 'Lifestyle and Fashion'), ('Business', 'Business and Entrepreneurship'), ('Science', 'Science and Innovation'), ('Entertainment', 'Entertainment and Pop Culture'), ('Education', 'Education and Learning'), ('Sports', 'Sports and Fitness'), ('Travel', 'Travel and Adventure'), ('Other', 'Other')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
