# Generated by Django 5.0.2 on 2024-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='otp_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
